### ISSUE TITLE
Regression problems in OmniPred.

### ISSUE THREAD

**Issue by jtb-7799** [google-research/optformer#123]
I want to ask if, when fine-tuning a regression task in the materials field using OmniPred, I only need to place the corresponding data into vz.ProblemAndTrials, or do I need to create a new vocabulary for chemical elements?

**Comment by xingyousong** [comment]
Take a look at this test: https://github.com/google-research/optformer/blob/main/optformer/omnipred/omnipred_test.py#L28

You can inject your own:

1. Featurizer (i.e. a converter from any object into a TensorDict of string values) - you don't need to use any of the VIzier APIs.
2. Vocabulary file (I recommend using default T5X vocabulary file). The vocabulary will be amended by custom y-representation tokens, e.g. <+>,<->,<0>,<1>,... 

Because at the end of the day, you need a `tf.Dataset` where elements are of the form `{"inputs": x, "targets": y}` where `x` is some string representation of your features, and `y` is of form e.g. `<+><3><4><5><E-2>` which can be obtained using our `[DigitByDigitFloatTokenSerializer](https://github.com/google-research/optformer/blob/main/optformer/common/serialization/numeric/tokens.py#L27-L129)`

Hope this helps,
- Richard
