### ISSUE TITLE
HPO-B results

### ISSUE THREAD

**Issue by SamuelGabriel** [google-research/optformer#13]
We wanted to include your HPO-B results in a paper, but realized that you start lower than all other baselines in HPO-B. Could it be that you did not use the 5 initial seeds of HPO-B?

**Comment by yutianc-dm** [comment]
Sorry for the late reply. We used the 5 initial seeds. Which method did you refer to?

**Comment by SamuelGabriel** [comment]
Mmh if you look in our paper, where we used the jsons from you, you can see that after the initial 5 seeds you are better than the rest. But maybe you just use a different way of sampling!? I talk about figure 9 of https://proceedings.mlr.press/v202/muller23a/muller23a.pdf

**Comment by yutianc-dm** [comment]
Reading your paper, it seems you use the original discrete setting of HPO-B where an optimizer chooses suggestions from a discrete set of hyperparameters. Because OptFormer is trained as a policy to propose its own hyperparameters, we use the continuous variant of HPO-B (section 5.4 in https://arxiv.org/abs/2106.06257) so that it doesn't have to choose from a discrete set. It's described at the beginning of section 5 in our OptFormer paper.

The optimization curves could be very different in the discrete and continuous settings. E.g. for some search space, the hyperparameter is not mapped to the log-domain by the HPO-B authors but the discrete suggestions are actually collected more uniformly in the log-domain. It makes search in the continuous space more difficult than choosing from a discrete set.
