### ISSUE TITLE
OmniPred question

### ISSUE THREAD

**Issue by hellobigorange** [google-research/optformer#133]
Hi, can you help me with a confusing question
We have ten devices with about a few hundred pieces of data per device, and now we want to get characteristic curves for each of the 10 devices individually. Previously we used to train a separate model for each device, but this way the migration of the model is poor (when we get a new device we need to retrain the model). Seeing the article you wrote OmniPred, we started thinking if we can use OmniPred modeling for small sample migration learning?

But since the sample size is really small, I feel that OmniPred might not work well, so I would like to get your opinion. Do you think your model is applicable in this scenario.

**Comment by xingyousong** [comment]
Hi, just making sure I'm understanding your question - you have 10 "tasks" where each task ("device") has its own input space, and hundreds of offline evaluations (x,y). Since the input spaces to each of these tasks are different, you can't train a unified model over all these tasks' data.

If so, yes OmniPred is worth a shot - our paper shows that even with limited single-task data, OmniPred can be competitive against a traditional e.g. MLP or random forest.

Adding more training data to it (even from different tasks) could make it even better.
